exports.handler = function(event, context, callback) {
  const people = [
    "https://cantina.co/images/team/matt-chisholm/matt-chisholm.jpg",
    "https://cantina.co/images/team/adam-stachelek/adam-stachelek.jpg",
    "https://cantina.co/images/team/aaron-pollock/aaron-pollock.jpg",
    "https://cantina.co/images/team/aaron-stevenson/aaron-stevenson.jpg",
    "https://cantina.co/images/team/adam-kenger/adam-kenger.jpg",
    "https://cantina.co/images/team/alice-chiang/alice-chiang.jpg",
    "https://cantina.co/images/team/allison-sigrist/allison-sigrist.jpg",
    "https://cantina.co/images/team/amy-baron/amy-baron.jpg",
    "https://cantina.co/images/team/amy-perelberg/amy-perelberg.jpg",
    "https://cantina.co/images/team/andrei-savu/andrei-savu.jpg",
    "https://cantina.co/images/team/andy-parquette/andy-parquette.jpg",
    "https://cantina.co/images/team/breelle-scarano/breelle-scarano.jpg",
    "https://cantina.co/images/team/brian-keegan/brian-keegan.jpg",
    "https://cantina.co/images/team/brian-wilkinson/brian-wilkinson.jpg",
    "https://cantina.co/images/team/chris-lamothe/chris-lamothe.jpg",
    "https://cantina.co/images/team/clark-van-der-beken/clark-van-der-beken.jpg",
    "https://cantina.co/images/team/corey-roth/corey-roth.jpg",
    "https://cantina.co/images/team/cyrus-beer/cyrus-beer.jpg",
    "https://cantina.co/images/team/dakota-kim/dakota-kim.jpg",
    "https://cantina.co/images/team/daniel-bostwick/daniel-bostwick.jpg",
    "https://cantina.co/images/team/david-purdy/david-purdy.jpg",
    "https://cantina.co/images/team/david-putney/david-putney.jpg",
    "https://cantina.co/images/team/doug-reynolds/doug-reynolds.jpg",
    "https://cantina.co/images/team/erica-solari/erica-solari.jpg",
    "https://cantina.co/images/team/erin-jackson/erin-jackson.jpg",
    "https://cantina.co/images/team/gail-black-smith/gail-black-smith.jpg",
    "https://cantina.co/images/team/george-white/george-white.jpg",
    "https://cantina.co/images/team/greg-cataldo/greg-cataldo.jpg",
    "https://cantina.co/images/team/greg-genovese/greg-genovese.jpg",
    "https://cantina.co/images/team/ian-cox/ian-cox.jpg",
    "https://cantina.co/images/team/jaime-abramson/jaime-abramson.jpg",
    "https://cantina.co/images/team/janus-cole/janus-cole.jpg",
    "https://cantina.co/images/team/jay-dolan/jay-dolan.jpg",
    "https://cantina.co/images/team/jocelyn-fassett/jocelyn-fassett.jpg",
    "https://cantina.co/images/team/joe-walsmith/joe-walsmith.jpg",
    "https://cantina.co/images/team/joe-wilson/joe-wilson.jpg",
    "https://cantina.co/images/team/john-hurley/john-hurley.jpg",
    "https://cantina.co/images/team/justin-stuart/justin-stuart.jpg",
    "https://cantina.co/images/team/katrina-stropkay/katrina-stropkay.jpg",
    "https://cantina.co/images/team/kevin-scola/kevin-scola.jpg",
    "https://cantina.co/images/team/kimberlee-cloutier-blazzard/kimberlee-cloutier-blazzard.jpg",
    "https://cantina.co/images/team/kole-nunley/kole-nunley.jpg",
    "https://cantina.co/images/team/krista-siniscarco/krista-siniscarco.jpg",
    "https://cantina.co/images/team/linda-mateos-powell/linda-mateos-powell.jpg",
    "https://cantina.co/images/team/madeleine-fougere/madeleine-fougere.jpg",
    "https://cantina.co/images/team/marcela-rodriguez/marcela-rodriguez.jpg",
    "https://cantina.co/images/team/matt-stuehler/matt-stuehler.jpg",
    "https://cantina.co/images/team/matthew-crist/matthew-crist.jpg",
    "https://cantina.co/images/team/matthias-ferber/matthias-ferber.jpg",
    "https://cantina.co/images/team/maxwell-legocki/maxwell-legocki.jpg",
    "https://cantina.co/images/team/michael-bourne/michael-bourne.jpg",
    "https://cantina.co/images/team/michael-leonardo/michael-leonardo.jpg",
    "https://cantina.co/images/team/michael-novak/michael-novak.jpg",
    "https://cantina.co/images/team/mike-kivikoski/mike-kivikoski.jpg",
    "https://cantina.co/images/team/pamela-lindahl/pamela-lindahl.jpg",
    "https://cantina.co/images/team/paul-demers/paul-demers.jpg",
    "https://cantina.co/images/team/pavithra-counsell/pavithra-counsell.jpg",
    "https://cantina.co/images/team/preeti-lekha/preeti-lekha.jpg",
    "https://cantina.co/images/team/randy-duke/randy-duke.jpg",
    "https://cantina.co/images/team/sam-margolis/sam-margolis.jpg",
    "https://cantina.co/images/team/sam-moore/sam-moore.jpg",
    "https://cantina.co/images/team/sam-morrow/sam-morrow.jpg",
    "https://cantina.co/images/team/scott-doxey/scott-doxey.jpg",
    "https://cantina.co/images/team/shaun-gummere/shaun-gummere.jpg",
    "https://cantina.co/images/team/shawn-neacy/shawn-neacy.jpg",
    "https://cantina.co/images/team/shukti-shaikh/shukti-shaikh.jpg",
    "https://cantina.co/images/team/stephen-nawrocki/stephen-nawrocki.jpg",
    "https://cantina.co/images/team/steve-myers/steve-myers.jpg",
    "https://cantina.co/images/team/steve-zarrella/steve-zarrella.jpg",
    "https://cantina.co/images/team/steven-telio/steven-telio.jpg",
    "https://cantina.co/images/team/taylore-thornton/taylore-thornton.jpg",
    "https://cantina.co/images/team/virginia-wood/virginia-wood.jpg",
    "https://cantina.co/images/team/wayne-elgin/wayne-elgin.jpg",
    "https://cantina.co/images/team/willy-mello/willy-mello.jpg",
  ];
  const {searchName} = event.queryStringParameters;
  const found = people.filter(function(person) {
    return person.includes(searchName)
  })



  callback(null, {
    statusCode: 200,
    body: JSON.stringify(found)
  })
}